name: CD - Deploy to Server

on:
  workflow_run:
    workflows: ["CI Build and Push to GHCR"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Используем runner на сервере
    
    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin
      
      - name: Pull and restart containers
        run: |
          cd /home/deployer/deploy/is-stack
          docker compose pull
          docker compose up -d
          docker image prune -f
      
      - name: Check version
        run: |
          sleep 5
          curl http://localhost:5000/version
